- name: Quick Start WSL
  hosts: wsl
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nodejs
  pre_tasks:
    - name: Update packages
      ansible.builtin.package:
        name: '*'
        state: latest
  tasks:
    - name: Install lunarvim
      ansible.builtin.include_role: lunarvim
