- name: Install prerequisites
  ansible.builtin.package:
    state: present
    pkg:
      - git-all
      - make
      - python3
      - python3-pip
      - ripgrep

- name: Install Rust
  ansible.builtin.shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  args:
    executable: /bin/bash
